declare namespace NodeJS {
  interface ProcessEnv {
    MONGODB_DB: string
    MONGODB_URI: string
    JWT_SECRET: string
    NEXMO_API_KEY: string
    NEXMO_API_SECRET: string
    NEXMO_APPLICATION_ID: string
    NEXMO_PUBLIC_KEY: string
    NEXMO_PRIVATE_KEY: string
    SECRET_COOKIE_PASSWORD: string
    NEXT_PUBLIC_GOOGLE_AUTH_API_KEY: string
    NEXT_PUBLIC_GOOGLE_AUTH_CLIENT_ID: string
    NEXT_PUBLIC_GOOGLE_AUTH_CLIENT_SECRET: string
    NEXT_PUBLIC_GOOGLE_AUTH_REDIRECT_URL: string
    NEXT_PUBLIC_PAYSTACK_PUBLIC: string
    NEXT_PUBLIC_PAYSTACK_SECRET: string
    NEXT_PUBLIC_FIREBASE_API_KEY: string
    NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: string
    NEXT_PUBLIC_FIREBASE_PROJECT_ID: string
    NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: string
    NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: string
    NEXT_PUBLIC_FIREBASE_APP_ID: string
    NEXT_PUBLIC_FIREBASE_MEASURING_ID: string
  }
}
